### ISSUE TITLE
No podspec found for `@boterop` in `../node_modules/@boterop/react-native-background-timer`

### ISSUE THREAD

**Issue by sanduluca** [boterop/react-native-background-timer#13]
I get the following error when I try to install the pods
```bash
app git:(timer) ✗ bundle exec pod install --project-directory=ios 

Analyzing dependencies
[!] No podspec found for `@boterop` in `../node_modules/@boterop/react-native-background-timer`
```

"react-native": "0.72.12",
"@boterop/react-native-background-timer": "^2.5.1",

**Comment by ivanoikon** [comment]
Same problem here, package is unusable on ios

**Comment by boterop** [comment]
I'm very sorry about that. I hope u can use this with iOS with the new version (v2.5.2) now published and available to update.
https://www.npmjs.com/package/@boterop/react-native-background-timer

Thanks @sanduluca
